version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis-data:
